"use client";
import {useEffect,useState} from "react";
import {Search,Plus,Clapperboard,FileText,Download,ArrowRight,RefreshCw,Check,ExternalLink,FolderOpen,Sparkles,LoaderCircle,Save} from "lucide-react";
import type {Project,Scene} from "@/lib/contracts";
type Topic={title:string;source:string;notes:string};
const statusLabel:Record<string,string>={collected:"소재 저장",scripted:"대본 검토",boarded:"스토리보드 완료"};
async function api(url:string,method="GET",body?:unknown){const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});const d:any=await r.json();if(!r.ok)throw new Error(d.error||"요청을 처리하지 못했습니다.");return d}
export default function Studio(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<string|null>(null),[step,setStep]=useState(0),[scenes,setScenes]=useState<Scene[]>([]),[dirty,setDirty]=useState(false);
 const [query,setQuery]=useState(""),[topics,setTopics]=useState<Topic[]>([]),[searched,setSearched]=useState(false),[manual,setManual]=useState(false),[form,setForm]=useState<Topic>({title:"",source:"",notes:""});
 const [busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[ready,setReady]=useState(false),[loading,setLoading]=useState(true);
 const current=projects.find(p=>p.id===selected);
 async function reload(){const d=await api("/api/projects");setProjects(d.projects);setReady(d.aiReady);return d.projects as Project[]}
 useEffect(()=>{reload().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 async function run(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setError("");setMessage("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"오류가 발생했습니다.")}finally{setBusy("")}}
 function open(p:Project){if(dirty&&!confirm("저장하지 않은 대본 변경을 버리고 이동할까요?"))return;setSelected(p.id);setScenes(JSON.parse(p.scenes));setDirty(false);setStep(p.board?2:1);setMessage("");setError("")}
 async function add(t:Topic){const d=await api("/api/projects","POST",t);const list=await reload();const p=list.find(x=>x.id===d.id);if(p)open(p);setManual(false);setForm({title:"",source:"",notes:""});setMessage("소재를 저장했습니다. 대본을 생성해 보세요.")}
 async function save(){if(!current)return;await api("/api/projects/"+current.id,"PATCH",{revision:current.revision,scenes});await reload();setDirty(false);setMessage("대본을 저장했습니다.")}
 async function generate(action:"script"|"board"){if(!current)return;if(action==="script"&&scenes.length&&!confirm("현재 대본을 새로 생성한 대본으로 바꿀까요?"))return;await api("/api/projects/"+current.id,"POST",{action,revision:current.revision});const list=await reload();const p=list.find(x=>x.id===current.id);if(p){setScenes(JSON.parse(p.scenes));setDirty(false);setStep(action==="board"?2:1)}setMessage(action==="board"?"스토리보드가 완성됐습니다.":"대본을 생성했습니다. 사실관계와 표현을 확인해 주세요.")}
 function edit(i:number,k:keyof Scene,v:string|number){setScenes(s=>s.map((x,n)=>n===i?{...x,[k]:v}:x));setDirty(true)}
 function fresh(){if(dirty&&!confirm("저장하지 않은 대본 변경을 버릴까요?"))return;setSelected(null);setDirty(false);setStep(0);setError("");setMessage("")}
 return <div className="shell">
 <aside className="sidebar"><div className="brand"><span className="brandmark"><Clapperboard size={23}/></span><div>쇼츠머신<small>CREATOR STUDIO</small></div></div>
 <button className="newbutton" onClick={fresh} disabled={!!busy}><Plus size={18}/>새 소재 찾기</button>
 <div className="section-label">나의 제작실 <span>{projects.length}</span></div>
 <div className="projectlist">{projects.map(p=><button key={p.id} className={"project "+(selected===p.id?"selected":"")} onClick={()=>open(p)} disabled={!!busy}><FileText size={17}/><span>{p.title}<small>{statusLabel[p.status]}</small></span></button>)}
 {!loading&&!projects.length&&<p className="side-empty">첫 소재를 저장하면<br/>여기에 쌓입니다.</p>}</div>
 <div className="account"><span className="avatar">나</span><div>개인 제작실<small>관리자 전용</small></div><span className="private">PRIVATE</span></div></aside>
 <div className="workspace"><header className="topbar"><span>제작실 <span className="divider">/</span> <b>{current?"콘텐츠 편집":"소재 탐색"}</b></span><button className="textbutton" disabled={!!busy||dirty} onClick={()=>run("불러오는 중",async()=>{const list=await reload();if(current){const p=list.find(x=>x.id===current.id);if(p)setScenes(JSON.parse(p.scenes))}setMessage("최신 작업을 불러왔습니다.")})}><RefreshCw size={15}/>새로고침</button></header>
 <main><div className="heading"><div><p className="eyebrow">SHORTS WORKSPACE</p><h1>{current?current.title:"다음 쇼츠, 무엇으로 만들까요?"}</h1><p className="subtitle">{current?"소재를 대본으로, 대본을 한 장의 스토리보드로.":"흥미로운 사실을 찾고, 나만의 이야기로 다듬어 보세요."}</p></div><span className="format">9:16 SHORTS <span>·</span> 오리 진행자</span></div>
 <nav className="steps" aria-label="제작 단계">{["소재 찾기","대본 확인 · 편집","스토리보드"].map((v,i)=><button key={v} className={step===i?"active":""} disabled={!!busy||(i>0&&!current)} onClick={()=>setStep(i)}><span>{i+1}</span>{v}{i<2&&<ArrowRight size={16}/>}</button>)}</nav>
 {error&&<div className="notice error" role="alert">{error}{error.includes("로그인")&&<a href="/signin-with-chatgpt?return_to=/" target="_top">로그인하기</a>}</div>}
 {message&&<div className="notice success" role="status"><Check size={17}/>{message}</div>}
 {busy&&<div className="notice working" role="status"><LoaderCircle className="spin" size={18}/>{busy}{busy.includes("스토리보드")&&" · 잠시 걸릴 수 있습니다. 이 화면을 유지해 주세요."}</div>}
 {!loading&&!ready&&<div className="notice">AI 연결을 준비 중입니다. 직접 소재를 저장할 수 있습니다.</div>}
 {step===0&&<><section className="searchbox"><div className="cardtitle"><Search size={21}/><h2>소재 탐색</h2><span>출처와 함께 찾기</span></div><form onSubmit={e=>{e.preventDefault();run("소재를 찾는 중",async()=>{const d=await api("/api/search","POST",{query});setTopics(d.topics);setSearched(true)})}}><div className="searchrow"><input aria-label="소재 검색어" value={query} maxLength={200} minLength={2} required onChange={e=>setQuery(e.target.value)} placeholder="예: 신기한 동물 행동, 놀라운 세계 기록"/><button className="primary" disabled={!!busy||!ready}><Sparkles size={17}/>소재 찾기</button></div></form><div className="suggestions"><span>이런 주제는 어때요?</span>{["동물의 반전 행동","놀라운 과학 발견","독특한 세계 기록"].map(q=><button key={q} onClick={()=>setQuery(q)}>{q}</button>)}</div></section>
 <div className="resulthead"><h2>{searched?"검색한 소재":"직접 찾은 이야기도 시작할 수 있어요"}</h2><button className="secondary" disabled={!!busy} onClick={()=>setManual(!manual)}><Plus size={17}/>소재 직접 입력</button></div>
 {manual&&<form className="manual card" onSubmit={e=>{e.preventDefault();run("소재 저장 중",()=>add(form))}}><label>제목<input required maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>출처 링크<input required type="url" placeholder="https://" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label>확인한 사실 · 원문 발췌<textarea required minLength={20} maxLength={12000} rows={5} placeholder="대본의 근거가 될 내용을 20자 이상 입력하세요." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" disabled={!!busy}>소재 저장<ArrowRight size={16}/></button></form>}
 <div className="topics">{topics.map((t,i)=><article className="topic card" key={t.source+i}><div className="topicnum">IDEA {String(i+1).padStart(2,"0")}</div><h3>{t.title}</h3><p>{t.notes}</p><div className="topicbottom"><a href={t.source} target="_blank" rel="noreferrer">원문 확인<ExternalLink size={14}/></a><button className="secondary" disabled={!!busy} onClick={()=>run("소재 저장 중",()=>add(t))}>이 소재로 만들기<ArrowRight size={15}/></button></div></article>)}</div>
 {searched&&!topics.length&&<div className="empty"><Search size={32}/><h3>검색 결과가 없습니다</h3><p>검색어를 바꾸거나 직접 소재를 입력해 주세요.</p></div>}
 {!searched&&!manual&&<div className="startguide"><div className="guideicon"><FolderOpen size={30}/></div><h3>좋은 소재 하나면 충분합니다</h3><p>관심 있는 주제를 검색하거나 기사 내용을 직접 넣어주세요.<br/>대본을 먼저 검토한 뒤 스토리보드를 생성합니다.</p><div className="guideflow"><span>01 <b>사실과 출처</b></span><span>02 <b>8컷 대본</b></span><span>03 <b>한 장으로 확인</b></span></div></div>}</>}
 {step===1&&current&&<><div className="editorhead"><div><h2>대본 편집</h2><p>{scenes.length?scenes.reduce((n,s)=>n+s.seconds,0)+"초 · 8컷 · "+(dirty?"저장하지 않은 변경":"저장된 대본"):"출처 내용을 바탕으로 첫 대본을 만들어 보세요."}</p></div><div className="actions"><button className="secondary" disabled={!!busy||!ready||!!current.lock} onClick={()=>run("대본 생성 중",()=>generate("script"))}><Sparkles size={16}/>{scenes.length?"대본 다시 생성":"AI 대본 생성"}</button>{scenes.length>0&&<button className="primary" disabled={!!busy||!dirty} onClick={()=>run("대본 저장 중",save)}><Save size={16}/>변경 저장</button>}</div></div>
 <details className="source card"><summary>근거 자료 확인 <ExternalLink size={14}/></summary><a href={current.source} target="_blank" rel="noreferrer">{current.source}</a><p>{current.notes}</p></details>
 {!scenes.length&&<div className="empty"><FileText size={34}/><h3>아직 대본이 없습니다</h3><p>AI 대본 생성을 누르면 훅부터 마지막 한마디까지 8컷으로 구성합니다.</p></div>}
 <div className="scenes">{scenes.map((s,i)=><article className="scene card" key={i}><div className="scenenum"><b>{String(i+1).padStart(2,"0")}</b><span>{i===0?"HOOK":i===7?"ENDING":"SCENE"}</span><label><input aria-label={i+1+"컷 시간"} type="number" min={1} max={15} value={s.seconds} disabled={!!busy} onChange={e=>edit(i,"seconds",Number(e.target.value))}/> 초</label></div><div className="scenefields"><label>내레이션<textarea value={s.narration} maxLength={500} disabled={!!busy} onChange={e=>edit(i,"narration",e.target.value)} rows={2}/></label><div className="visualfields"><label>화면 연출<textarea value={s.visual} maxLength={600} disabled={!!busy} onChange={e=>edit(i,"visual",e.target.value)} rows={2}/></label><label>오리 리액션<textarea value={s.reaction} maxLength={150} disabled={!!busy} onChange={e=>edit(i,"reaction",e.target.value)} rows={2}/></label></div></div></article>)}</div>
 {scenes.length>0&&<div className="approval"><div><b>대본 확인을 마쳤나요?</b><p>저장된 대본으로 스토리보드 한 장을 생성합니다.</p></div><button className="primary" disabled={!!busy||dirty||!ready||!!current.lock} onClick={()=>run("스토리보드 생성 중",()=>generate("board"))}>대본 승인 · 스토리보드 생성<ArrowRight size={17}/></button></div>}</>}
 {step===2&&current&&<><div className="editorhead"><div><h2>스토리보드</h2><p>4 × 2 구성 · 8컷 · 연출 검토용 이미지</p></div>{current.board&&!dirty&&<a className="primary" href={"/api/projects/"+current.id+"/download"}><Download size={17}/>PNG 다운로드</a>}</div>
 {dirty&&<div className="notice">대본에 저장하지 않은 변경이 있습니다. 저장 후 스토리보드를 다시 생성해 주세요.</div>}
 {current.board?<div className="board card"><img src={"/api/projects/"+current.id+"/download?inline=1&v="+current.updated} alt={current.title+"의 8컷 스토리보드"}/><p>AI 연출 이미지 · 실제 사건의 증거 자료가 아닙니다. 컷 순서와 연출은 대본과 함께 확인해 주세요.</p></div>:<div className="empty"><Clapperboard size={36}/><h3>대본을 확인한 뒤 생성해 주세요</h3><p>이미지 생성은 대본 승인 후에만 진행합니다.</p><button className="secondary" onClick={()=>setStep(1)}>대본 검토하기<ArrowRight size={16}/></button></div>}
 {current.board&&<div className="boardcaptions">{scenes.map((s,i)=><div key={i}><b>{String(i+1).padStart(2,"0")} · {s.seconds}초</b><p>{s.narration}</p></div>)}</div>}</>}
 <footer>쇼츠머신 MVP <span>소재 → 대본 → 스토리보드</span></footer></main></div></div>
}
